/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\git-project\\Document\\developing-guideline\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2b30e752",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b30e752").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-e4785c48",
    path: "/c/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e4785c48").then(next)
    },
  },
  {
    path: "/c/index.html",
    redirect: "/c/"
  },
  {
    name: "v-21d46c84",
    path: "/android/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21d46c84").then(next)
    },
  },
  {
    path: "/android/index.html",
    redirect: "/android/"
  },
  {
    name: "v-4dc35681",
    path: "/document/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4dc35681").then(next)
    },
  },
  {
    name: "v-0ad82d4c",
    path: "/document/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ad82d4c").then(next)
    },
  },
  {
    path: "/document/index.html",
    redirect: "/document/"
  },
  {
    name: "v-59dda2d1",
    path: "/document/introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59dda2d1").then(next)
    },
  },
  {
    name: "v-772ae8d2",
    path: "/document/sqlite3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-772ae8d2").then(next)
    },
  },
  {
    name: "v-4561aa31",
    path: "/document/serialport.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4561aa31").then(next)
    },
  },
  {
    name: "v-f9454e8c",
    path: "/electron/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f9454e8c").then(next)
    },
  },
  {
    path: "/electron/index.html",
    redirect: "/electron/"
  },
  {
    name: "v-03edcd3e",
    path: "/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03edcd3e").then(next)
    },
  },
  {
    path: "/git/index.html",
    redirect: "/git/"
  },
  {
    name: "v-0819e3ba",
    path: "/mobile/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0819e3ba").then(next)
    },
  },
  {
    path: "/mobile/index.html",
    redirect: "/mobile/"
  },
  {
    name: "v-f85d5ecc",
    path: "/nodejs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f85d5ecc").then(next)
    },
  },
  {
    path: "/nodejs/index.html",
    redirect: "/nodejs/"
  },
  {
    name: "v-d088c1b8",
    path: "/react/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d088c1b8").then(next)
    },
  },
  {
    path: "/react/index.html",
    redirect: "/react/"
  },
  {
    name: "v-5f093b45",
    path: "/react/basics_character.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f093b45").then(next)
    },
  },
  {
    name: "v-3d367dba",
    path: "/safety/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d367dba").then(next)
    },
  },
  {
    path: "/safety/index.html",
    redirect: "/safety/"
  },
  {
    name: "v-5fc9b19a",
    path: "/server/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fc9b19a").then(next)
    },
  },
  {
    path: "/server/index.html",
    redirect: "/server/"
  },
  {
    name: "v-10044c2a",
    path: "/sharing/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10044c2a").then(next)
    },
  },
  {
    path: "/sharing/index.html",
    redirect: "/sharing/"
  },
  {
    name: "v-68aecbc8",
    path: "/specification/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68aecbc8").then(next)
    },
  },
  {
    path: "/specification/index.html",
    redirect: "/specification/"
  },
  {
    name: "v-49cb5715",
    path: "/specification/common.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49cb5715").then(next)
    },
  },
  {
    name: "v-5ba57964",
    path: "/specification/common/css_jdc_fd_guide_css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ba57964").then(next)
    },
  },
  {
    name: "v-638963dc",
    path: "/specification/common/html_jdc_fd_web_final_2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-638963dc").then(next)
    },
  },
  {
    name: "v-2d3e46e4",
    path: "/specification/common/image_jdc_fd_guide_image.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d3e46e4").then(next)
    },
  },
  {
    name: "v-19645d24",
    path: "/specification/common/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19645d24").then(next)
    },
  },
  {
    name: "v-143beea4",
    path: "/specification/common/name_jdc_fd_guide_name.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-143beea4").then(next)
    },
  },
  {
    name: "v-d140ba52",
    path: "/specification/contributing.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d140ba52").then(next)
    },
  },
  {
    name: "v-3274fcd9",
    path: "/specification/css_code.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3274fcd9").then(next)
    },
  },
  {
    name: "v-2e551217",
    path: "/specification/css_query.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e551217").then(next)
    },
  },
  {
    name: "v-2895734f",
    path: "/specification/css_note.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2895734f").then(next)
    },
  },
  {
    name: "v-97ac1b12",
    path: "/specification/css_reset.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-97ac1b12").then(next)
    },
  },
  {
    name: "v-3c38e252",
    path: "/specification/css_sass.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c38e252").then(next)
    },
  },
  {
    name: "v-0fe4f7a2",
    path: "/specification/css_webkit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fe4f7a2").then(next)
    },
  },
  {
    name: "v-1e738192",
    path: "/specification/html_code.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e738192").then(next)
    },
  },
  {
    name: "v-6ece6657",
    path: "/specification/html_note.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ece6657").then(next)
    },
  },
  {
    name: "v-00d0fd52",
    path: "/specification/html_template.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00d0fd52").then(next)
    },
  },
  {
    name: "v-5fcd2cf5",
    path: "/specification/image_format.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fcd2cf5").then(next)
    },
  },
  {
    name: "v-1e36c577",
    path: "/specification/html_webapp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e36c577").then(next)
    },
  },
  {
    name: "v-524e78ce",
    path: "/specification/image_import.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-524e78ce").then(next)
    },
  },
  {
    name: "v-f70ba212",
    path: "/specification/image_quality.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f70ba212").then(next)
    },
  },
  {
    name: "v-75f2a3be",
    path: "/specification/image_size.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75f2a3be").then(next)
    },
  },
  {
    name: "v-7b5d2ab7",
    path: "/specification/js_code.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b5d2ab7").then(next)
    },
  },
  {
    name: "v-0ce6b537",
    path: "/specification/issues.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ce6b537").then(next)
    },
  },
  {
    name: "v-370f0e57",
    path: "/specification/js_language.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-370f0e57").then(next)
    },
  },
  {
    name: "v-0a1d350b",
    path: "/specification/js_vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a1d350b").then(next)
    },
  },
  {
    name: "v-2016ac19",
    path: "/specification/js_react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2016ac19").then(next)
    },
  },
  {
    name: "v-604d024d",
    path: "/specification/name_classname.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-604d024d").then(next)
    },
  },
  {
    name: "v-a4d3df0e",
    path: "/specification/name_dir.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a4d3df0e").then(next)
    },
  },
  {
    name: "v-431159c6",
    path: "/specification/name_image.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-431159c6").then(next)
    },
  },
  {
    name: "v-e34e29ba",
    path: "/specification/name_htmlcss.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e34e29ba").then(next)
    },
  },
  {
    name: "v-46a134ba",
    path: "/test/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46a134ba").then(next)
    },
  },
  {
    path: "/test/index.html",
    redirect: "/test/"
  },
  {
    name: "v-18eb71d6",
    path: "/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18eb71d6").then(next)
    },
  },
  {
    path: "/vue/index.html",
    redirect: "/vue/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]