/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "湘亭科技软件开发指南",
  "description": "Developing-Guideline 手册",
  "base": "/Document/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/logo.png",
        "heroText": "湘亭科技软件开发指南",
        "tagline": "你的代码应该是给下一个开发者的情书，而不是战书……",
        "actionText": "快速上手 →",
        "actionLink": "/specification/",
        "features": [
          {
            "title": "编程规约",
            "details": "为实现代码一致性和最佳实践，通过代码风格的一致性，降低维护代码的成本以及改善多人协作的效率。"
          },
          {
            "title": "技术指南",
            "details": "遵守最佳实践，确保程序性能得到最佳优化与实现高效的代码。"
          },
          {
            "title": "持续更新",
            "details": "由内部开发者根据技术的持续迭代更新此文档，保证团队所有成员掌握最新的开发方式。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2021-杭州湘亭科技有限公司"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2b30e752",
      "path": "/"
    },
    {
      "title": "测试相关文档说明",
      "frontmatter": {},
      "regularPath": "/c/",
      "relativePath": "c/README.md",
      "key": "v-e4785c48",
      "path": "/c/"
    },
    {
      "title": "Android相关文档说明",
      "frontmatter": {},
      "regularPath": "/android/",
      "relativePath": "android/README.md",
      "key": "v-21d46c84",
      "path": "/android/"
    },
    {
      "title": "Git",
      "frontmatter": {},
      "regularPath": "/document/git.html",
      "relativePath": "document/git.md",
      "key": "v-4dc35681",
      "path": "/document/git.html",
      "headers": [
        {
          "level": 2,
          "title": "Debian/Ubuntu",
          "slug": "debian-ubuntu"
        }
      ]
    },
    {
      "title": "说明",
      "frontmatter": {},
      "regularPath": "/document/",
      "relativePath": "document/README.md",
      "key": "v-0ad82d4c",
      "path": "/document/",
      "headers": [
        {
          "level": 2,
          "title": "How It Works",
          "slug": "how-it-works"
        },
        {
          "level": 2,
          "title": "Features",
          "slug": "features"
        },
        {
          "level": 2,
          "title": "Why Not ...?",
          "slug": "why-not"
        },
        {
          "level": 3,
          "title": "Nuxt",
          "slug": "nuxt"
        },
        {
          "level": 3,
          "title": "Docsify / Docute",
          "slug": "docsify-docute"
        },
        {
          "level": 3,
          "title": "Hexo",
          "slug": "hexo"
        },
        {
          "level": 3,
          "title": "GitBook",
          "slug": "gitbook"
        }
      ]
    },
    {
      "title": "serialport",
      "frontmatter": {},
      "regularPath": "/document/introduction.html",
      "relativePath": "document/introduction.md",
      "key": "v-59dda2d1",
      "path": "/document/introduction.html"
    },
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/document/sqlite3.html",
      "relativePath": "document/sqlite3.md",
      "key": "v-772ae8d2",
      "path": "/document/sqlite3.html"
    },
    {
      "title": "serialport",
      "frontmatter": {},
      "regularPath": "/document/serialport.html",
      "relativePath": "document/serialport.md",
      "key": "v-4561aa31",
      "path": "/document/serialport.html"
    },
    {
      "title": "Electron相关文档说明",
      "frontmatter": {},
      "regularPath": "/electron/",
      "relativePath": "electron/README.md",
      "key": "v-f9454e8c",
      "path": "/electron/"
    },
    {
      "title": "Git相关文档说明",
      "frontmatter": {},
      "regularPath": "/git/",
      "relativePath": "git/README.md",
      "key": "v-03edcd3e",
      "path": "/git/"
    },
    {
      "title": "移动端相关文档说明",
      "frontmatter": {},
      "regularPath": "/mobile/",
      "relativePath": "mobile/README.md",
      "key": "v-0819e3ba",
      "path": "/mobile/"
    },
    {
      "title": "node.js 相关文档说明",
      "frontmatter": {},
      "regularPath": "/nodejs/",
      "relativePath": "nodejs/README.md",
      "key": "v-f85d5ecc",
      "path": "/nodejs/"
    },
    {
      "title": "React相关文档说明",
      "frontmatter": {},
      "regularPath": "/react/",
      "relativePath": "react/README.md",
      "key": "v-d088c1b8",
      "path": "/react/"
    },
    {
      "title": "历史背景及特性",
      "frontmatter": {},
      "regularPath": "/react/basics_character.html",
      "relativePath": "react/basics_character.md",
      "key": "v-5f093b45",
      "path": "/react/basics_character.html"
    },
    {
      "title": "网络安全相关文档说明",
      "frontmatter": {},
      "regularPath": "/safety/",
      "relativePath": "safety/README.md",
      "key": "v-3d367dba",
      "path": "/safety/"
    },
    {
      "title": "服务器相关文档说明",
      "frontmatter": {},
      "regularPath": "/server/",
      "relativePath": "server/README.md",
      "key": "v-5fc9b19a",
      "path": "/server/"
    },
    {
      "title": "技术分享相关文档说明",
      "frontmatter": {},
      "regularPath": "/sharing/",
      "relativePath": "sharing/README.md",
      "key": "v-10044c2a",
      "path": "/sharing/"
    },
    {
      "title": "开始使用",
      "frontmatter": {},
      "regularPath": "/specification/",
      "relativePath": "specification/README.md",
      "key": "v-68aecbc8",
      "path": "/specification/",
      "headers": [
        {
          "level": 2,
          "title": "简介",
          "slug": "简介"
        },
        {
          "level": 3,
          "title": "命名规范",
          "slug": "命名规范"
        },
        {
          "level": 3,
          "title": "HTML规范",
          "slug": "html规范"
        },
        {
          "level": 3,
          "title": "CSS规范",
          "slug": "css规范"
        },
        {
          "level": 3,
          "title": "JavaScript 规范",
          "slug": "javascript-规范"
        },
        {
          "level": 3,
          "title": "图片规范",
          "slug": "图片规范"
        },
        {
          "level": 3,
          "title": "Vue 规范",
          "slug": "vue-规范"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/specification/common.html",
      "relativePath": "specification/common.md",
      "key": "v-49cb5715",
      "path": "/specification/common.html",
      "headers": [
        {
          "level": 2,
          "title": "title: 通用设置",
          "slug": "title-通用设置"
        }
      ]
    },
    {
      "title": "CSS规范",
      "frontmatter": {},
      "regularPath": "/specification/common/css_jdc_fd_guide_css.html",
      "relativePath": "specification/common/css_jdc_fd_guide_css.md",
      "key": "v-5ba57964",
      "path": "/specification/common/css_jdc_fd_guide_css.html",
      "headers": [
        {
          "level": 2,
          "title": "CSS规范",
          "slug": "css规范"
        },
        {
          "level": 3,
          "title": "代码规范",
          "slug": "代码规范"
        },
        {
          "level": 3,
          "title": "注释规范",
          "slug": "注释规范"
        },
        {
          "level": 3,
          "title": "SASS规范",
          "slug": "sass规范"
        },
        {
          "level": 3,
          "title": "重置样式",
          "slug": "重置样式"
        },
        {
          "level": 3,
          "title": "媒体查询",
          "slug": "媒体查询"
        }
      ]
    },
    {
      "title": "前端开发编码规范",
      "frontmatter": {},
      "regularPath": "/specification/common/html_jdc_fd_web_final_2.html",
      "relativePath": "specification/common/html_jdc_fd_web_final_2.md",
      "key": "v-638963dc",
      "path": "/specification/common/html_jdc_fd_web_final_2.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML规范",
          "slug": "html规范"
        },
        {
          "level": 3,
          "title": "WebApp Meta 标签设置(iOS)",
          "slug": "webapp-meta-标签设置-ios"
        }
      ]
    },
    {
      "title": "图片规范",
      "frontmatter": {},
      "regularPath": "/specification/common/image_jdc_fd_guide_image.html",
      "relativePath": "specification/common/image_jdc_fd_guide_image.md",
      "key": "v-2d3e46e4",
      "path": "/specification/common/image_jdc_fd_guide_image.html",
      "headers": [
        {
          "level": 2,
          "title": "图片规范",
          "slug": "图片规范"
        },
        {
          "level": 3,
          "title": "图片格式",
          "slug": "图片格式"
        },
        {
          "level": 3,
          "title": "图片大小",
          "slug": "图片大小"
        },
        {
          "level": 3,
          "title": "图片质量",
          "slug": "图片质量"
        },
        {
          "level": 3,
          "title": "图片引入",
          "slug": "图片引入"
        },
        {
          "level": 3,
          "title": "CSS Sprites VS Data URIs",
          "slug": "css-sprites-vs-data-uris"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/specification/common/markdown.html",
      "relativePath": "specification/common/markdown.md",
      "key": "v-19645d24",
      "path": "/specification/common/markdown.html",
      "headers": [
        {
          "level": 2,
          "title": "title: Markdown手册",
          "slug": "title-markdown手册"
        },
        {
          "level": 2,
          "title": "Headings",
          "slug": "headings"
        },
        {
          "level": 2,
          "title": "h2 Heading",
          "slug": "h2-heading"
        },
        {
          "level": 3,
          "title": "h3 Heading",
          "slug": "h3-heading"
        },
        {
          "level": 2,
          "title": "Horizontal Rules",
          "slug": "horizontal-rules"
        },
        {
          "level": 2,
          "title": "Body Copy",
          "slug": "body-copy"
        },
        {
          "level": 2,
          "title": "Emphasis",
          "slug": "emphasis"
        },
        {
          "level": 3,
          "title": "Bold",
          "slug": "bold"
        },
        {
          "level": 3,
          "title": "Italics",
          "slug": "italics"
        },
        {
          "level": 3,
          "title": "strikethrough",
          "slug": "strikethrough"
        },
        {
          "level": 2,
          "title": "Blockquotes",
          "slug": "blockquotes"
        },
        {
          "level": 2,
          "title": "Lists",
          "slug": "lists"
        },
        {
          "level": 3,
          "title": "Unordered",
          "slug": "unordered"
        },
        {
          "level": 3,
          "title": "Ordered",
          "slug": "ordered"
        },
        {
          "level": 2,
          "title": "Code",
          "slug": "code"
        },
        {
          "level": 3,
          "title": "Inline code",
          "slug": "inline-code"
        },
        {
          "level": 3,
          "title": "Indented code",
          "slug": "indented-code"
        },
        {
          "level": 3,
          "title": "Block code \"fences\"",
          "slug": "block-code-fences"
        },
        {
          "level": 3,
          "title": "Syntax highlighting",
          "slug": "syntax-highlighting"
        },
        {
          "level": 2,
          "title": "Tables",
          "slug": "tables"
        },
        {
          "level": 3,
          "title": "Right aligned text",
          "slug": "right-aligned-text"
        },
        {
          "level": 2,
          "title": "Links",
          "slug": "links"
        },
        {
          "level": 3,
          "title": "Basic link",
          "slug": "basic-link"
        },
        {
          "level": 3,
          "title": "Add a title",
          "slug": "add-a-title"
        },
        {
          "level": 3,
          "title": "Named Anchors",
          "slug": "named-anchors"
        },
        {
          "level": 2,
          "title": "Images",
          "slug": "images"
        }
      ]
    },
    {
      "title": "命名规范",
      "frontmatter": {},
      "regularPath": "/specification/common/name_jdc_fd_guide_name.html",
      "relativePath": "specification/common/name_jdc_fd_guide_name.md",
      "key": "v-143beea4",
      "path": "/specification/common/name_jdc_fd_guide_name.html",
      "headers": [
        {
          "level": 2,
          "title": "命名规范",
          "slug": "命名规范"
        },
        {
          "level": 3,
          "title": "目录命名",
          "slug": "目录命名"
        },
        {
          "level": 3,
          "title": "HTML/CSS文件命名",
          "slug": "html-css文件命名"
        },
        {
          "level": 3,
          "title": "图片命名",
          "slug": "图片命名"
        },
        {
          "level": 3,
          "title": "ClassName命名",
          "slug": "classname命名"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/specification/contributing.html",
      "relativePath": "specification/contributing.md",
      "key": "v-d140ba52",
      "path": "/specification/contributing.html",
      "headers": [
        {
          "level": 2,
          "title": "title: 贡献",
          "slug": "title-贡献"
        },
        {
          "level": 2,
          "title": "完善",
          "slug": "完善"
        },
        {
          "level": 3,
          "title": "开始之前",
          "slug": "开始之前"
        },
        {
          "level": 3,
          "title": "如何做？",
          "slug": "如何做"
        },
        {
          "level": 3,
          "title": "注意事项",
          "slug": "注意事项"
        },
        {
          "level": 2,
          "title": "问题反馈",
          "slug": "问题反馈"
        },
        {
          "level": 2,
          "title": "贡献者",
          "slug": "贡献者"
        }
      ]
    },
    {
      "title": "代码规范",
      "frontmatter": {},
      "regularPath": "/specification/css_code.html",
      "relativePath": "specification/css_code.md",
      "key": "v-3274fcd9",
      "path": "/specification/css_code.html",
      "headers": [
        {
          "level": 2,
          "title": "编码规范",
          "slug": "编码规范"
        },
        {
          "level": 3,
          "title": "文档内嵌样式表编码",
          "slug": "文档内嵌样式表编码"
        },
        {
          "level": 3,
          "title": "文档外链样式表编码",
          "slug": "文档外链样式表编码"
        },
        {
          "level": 3,
          "title": "样式表编码",
          "slug": "样式表编码"
        },
        {
          "level": 3,
          "title": "团队约定",
          "slug": "团队约定"
        },
        {
          "level": 2,
          "title": "代码风格",
          "slug": "代码风格"
        },
        {
          "level": 3,
          "title": "代码格式化",
          "slug": "代码格式化"
        },
        {
          "level": 3,
          "title": "代码大小写",
          "slug": "代码大小写"
        },
        {
          "level": 3,
          "title": "选择器",
          "slug": "选择器"
        },
        {
          "level": 3,
          "title": "代码缩进",
          "slug": "代码缩进"
        },
        {
          "level": 3,
          "title": "分号",
          "slug": "分号"
        },
        {
          "level": 3,
          "title": "代码易读性",
          "slug": "代码易读性"
        },
        {
          "level": 3,
          "title": "属性值引号",
          "slug": "属性值引号"
        },
        {
          "level": 3,
          "title": "属性书写顺序",
          "slug": "属性书写顺序"
        },
        {
          "level": 3,
          "title": "CSS3浏览器私有前缀写法",
          "slug": "css3浏览器私有前缀写法"
        }
      ]
    },
    {
      "title": "媒体查询",
      "frontmatter": {},
      "regularPath": "/specification/css_query.html",
      "relativePath": "specification/css_query.md",
      "key": "v-2e551217",
      "path": "/specification/css_query.html",
      "headers": [
        {
          "level": 2,
          "title": "常用查询语句",
          "slug": "常用查询语句"
        },
        {
          "level": 2,
          "title": "常用设备设置",
          "slug": "常用设备设置"
        },
        {
          "level": 3,
          "title": "iPhones",
          "slug": "iphones"
        },
        {
          "level": 3,
          "title": "Galaxy Phones",
          "slug": "galaxy-phones"
        },
        {
          "level": 3,
          "title": "HTC Phones",
          "slug": "htc-phones"
        },
        {
          "level": 3,
          "title": "iPads",
          "slug": "ipads"
        }
      ]
    },
    {
      "title": "注释规范",
      "frontmatter": {},
      "regularPath": "/specification/css_note.html",
      "relativePath": "specification/css_note.md",
      "key": "v-2895734f",
      "path": "/specification/css_note.html",
      "headers": [
        {
          "level": 3,
          "title": "团队约定",
          "slug": "团队约定"
        }
      ]
    },
    {
      "title": "重置样式",
      "frontmatter": {},
      "regularPath": "/specification/css_reset.html",
      "relativePath": "specification/css_reset.md",
      "key": "v-97ac1b12",
      "path": "/specification/css_reset.html",
      "headers": [
        {
          "level": 2,
          "title": "移动端",
          "slug": "移动端"
        },
        {
          "level": 2,
          "title": "PC端",
          "slug": "pc端"
        }
      ]
    },
    {
      "title": "SASS规范",
      "frontmatter": {},
      "regularPath": "/specification/css_sass.html",
      "relativePath": "specification/css_sass.md",
      "key": "v-3c38e252",
      "path": "/specification/css_sass.html",
      "headers": [
        {
          "level": 2,
          "title": "语法选用",
          "slug": "语法选用"
        },
        {
          "level": 3,
          "title": "SCSS",
          "slug": "scss"
        },
        {
          "level": 3,
          "title": "Sass",
          "slug": "sass"
        },
        {
          "level": 3,
          "title": "团队约定",
          "slug": "团队约定"
        },
        {
          "level": 2,
          "title": "编码格式",
          "slug": "编码格式"
        },
        {
          "level": 3,
          "title": "团队约定",
          "slug": "团队约定-2"
        },
        {
          "level": 2,
          "title": "SASS注释规范",
          "slug": "sass注释规范"
        },
        {
          "level": 3,
          "title": "团队约定",
          "slug": "团队约定-3"
        },
        {
          "level": 2,
          "title": "嵌套规范",
          "slug": "嵌套规范"
        },
        {
          "level": 3,
          "title": "选择器嵌套",
          "slug": "选择器嵌套"
        },
        {
          "level": 3,
          "title": "属性嵌套",
          "slug": "属性嵌套"
        },
        {
          "level": 2,
          "title": "变量",
          "slug": "变量"
        },
        {
          "level": 2,
          "title": "混合(mixin)",
          "slug": "混合-mixin"
        },
        {
          "level": 2,
          "title": "占位选择器 %",
          "slug": "占位选择器"
        },
        {
          "level": 2,
          "title": "extend 继承",
          "slug": "extend-继承"
        },
        {
          "level": 2,
          "title": "for 循环",
          "slug": "for-循环"
        },
        {
          "level": 2,
          "title": "each 循环",
          "slug": "each-循环"
        },
        {
          "level": 2,
          "title": "function 函数",
          "slug": "function-函数"
        },
        {
          "level": 2,
          "title": "运算规范",
          "slug": "运算规范"
        }
      ]
    },
    {
      "title": "移动端常用私有属性",
      "frontmatter": {},
      "regularPath": "/specification/css_webkit.html",
      "relativePath": "specification/css_webkit.md",
      "key": "v-0fe4f7a2",
      "path": "/specification/css_webkit.html",
      "headers": [
        {
          "level": 2,
          "title": "-webkit-scrollbar",
          "slug": "webkit-scrollbar"
        },
        {
          "level": 3,
          "title": "滚动条各块组成表现渲染的伪元素",
          "slug": "滚动条各块组成表现渲染的伪元素"
        },
        {
          "level": 3,
          "title": "滚动条各块组成的伪元素",
          "slug": "滚动条各块组成的伪元素"
        },
        {
          "level": 2,
          "title": "-webkit-touch-callout",
          "slug": "webkit-touch-callout"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性"
        },
        {
          "level": 2,
          "title": "-webkit-tap-highlight-color",
          "slug": "webkit-tap-highlight-color"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-2"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-2"
        },
        {
          "level": 2,
          "title": "-webkit-overflow-scrolling",
          "slug": "webkit-overflow-scrolling"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-3"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-3"
        },
        {
          "level": 2,
          "title": "-webkit-line-clamp",
          "slug": "webkit-line-clamp"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-4"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-4"
        },
        {
          "level": 2,
          "title": "-webkit-appearance",
          "slug": "webkit-appearance"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-5"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-5"
        },
        {
          "level": 2,
          "title": "-webkit-font-smoothing",
          "slug": "webkit-font-smoothing"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-6"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-6"
        },
        {
          "level": 2,
          "title": "-webkit-backface-visibility",
          "slug": "webkit-backface-visibility"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-7"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-7"
        },
        {
          "level": 2,
          "title": "-webkit-mask",
          "slug": "webkit-mask"
        },
        {
          "level": 3,
          "title": "使用语法",
          "slug": "使用语法"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-8"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-8"
        },
        {
          "level": 2,
          "title": "-webkit-user-select",
          "slug": "webkit-user-select"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-9"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-9"
        },
        {
          "level": 2,
          "title": "-webkit-user-modify",
          "slug": "webkit-user-modify"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-10"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-10"
        },
        {
          "level": 2,
          "title": "-webkit-text-stroke",
          "slug": "webkit-text-stroke"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-11"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-11"
        },
        {
          "level": 2,
          "title": "-webkit-text-fill-color",
          "slug": "webkit-text-fill-color"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-12"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-12"
        },
        {
          "level": 2,
          "title": "-webkit-text-size-adjust",
          "slug": "webkit-text-size-adjust"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-13"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-13"
        },
        {
          "level": 2,
          "title": "-webkit-marquee",
          "slug": "webkit-marquee"
        },
        {
          "level": 3,
          "title": "使用语法",
          "slug": "使用语法-2"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-14"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-14"
        },
        {
          "level": 2,
          "title": "-webkit-filter",
          "slug": "webkit-filter"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-15"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-15"
        },
        {
          "level": 2,
          "title": "-webkit-backdrop-filter",
          "slug": "webkit-backdrop-filter"
        },
        {
          "level": 3,
          "title": "属性值",
          "slug": "属性值-16"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-16"
        },
        {
          "level": 2,
          "title": "position:-webkit-sticky",
          "slug": "position-webkit-sticky"
        },
        {
          "level": 3,
          "title": "特性",
          "slug": "特性"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-17"
        },
        {
          "level": 2,
          "title": "-apple-system",
          "slug": "apple-system"
        },
        {
          "level": 3,
          "title": "兼容性",
          "slug": "兼容性-18"
        },
        {
          "level": 2,
          "title": "更多 WebKit CSS 属性",
          "slug": "更多-webkit-css-属性"
        }
      ]
    },
    {
      "title": "代码规范",
      "frontmatter": {},
      "regularPath": "/specification/html_code.html",
      "relativePath": "specification/html_code.md",
      "key": "v-1e738192",
      "path": "/specification/html_code.html",
      "headers": [
        {
          "level": 2,
          "title": "DOCTYPE 声明",
          "slug": "doctype-声明"
        },
        {
          "level": 3,
          "title": "团队约定",
          "slug": "团队约定"
        },
        {
          "level": 3,
          "title": "更多关于 DOCTYPE声明",
          "slug": "更多关于-doctype声明"
        },
        {
          "level": 2,
          "title": "页面语言LANG",
          "slug": "页面语言lang"
        },
        {
          "level": 3,
          "title": "团队约定",
          "slug": "团队约定-2"
        },
        {
          "level": 2,
          "title": "CHARSET",
          "slug": "charset"
        },
        {
          "level": 3,
          "title": "团队约定",
          "slug": "团队约定-3"
        },
        {
          "level": 2,
          "title": "元素及标签闭合",
          "slug": "元素及标签闭合"
        },
        {
          "level": 3,
          "title": "团队约定",
          "slug": "团队约定-4"
        },
        {
          "level": 2,
          "title": "书写风格",
          "slug": "书写风格"
        },
        {
          "level": 3,
          "title": "HTML代码大小写",
          "slug": "html代码大小写"
        },
        {
          "level": 3,
          "title": "类型属性",
          "slug": "类型属性"
        },
        {
          "level": 3,
          "title": "元素属性",
          "slug": "元素属性"
        },
        {
          "level": 3,
          "title": "特殊字符引用",
          "slug": "特殊字符引用"
        },
        {
          "level": 3,
          "title": "代码缩进",
          "slug": "代码缩进"
        },
        {
          "level": 3,
          "title": "纯数字输入框",
          "slug": "纯数字输入框"
        },
        {
          "level": 3,
          "title": "代码嵌套",
          "slug": "代码嵌套"
        }
      ]
    },
    {
      "title": "注释规范",
      "frontmatter": {},
      "regularPath": "/specification/html_note.html",
      "relativePath": "specification/html_note.md",
      "key": "v-6ece6657",
      "path": "/specification/html_note.html",
      "headers": [
        {
          "level": 2,
          "title": "遵循标准",
          "slug": "遵循标准"
        },
        {
          "level": 2,
          "title": "团队约定",
          "slug": "团队约定"
        },
        {
          "level": 3,
          "title": "单行注释",
          "slug": "单行注释"
        },
        {
          "level": 3,
          "title": "模块注释",
          "slug": "模块注释"
        },
        {
          "level": 3,
          "title": "嵌套模块注释",
          "slug": "嵌套模块注释"
        }
      ]
    },
    {
      "title": "文件模版",
      "frontmatter": {},
      "regularPath": "/specification/html_template.html",
      "relativePath": "specification/html_template.md",
      "key": "v-00d0fd52",
      "path": "/specification/html_template.html",
      "headers": [
        {
          "level": 2,
          "title": "HTML5标准模版",
          "slug": "html5标准模版"
        },
        {
          "level": 2,
          "title": "团队约定",
          "slug": "团队约定"
        },
        {
          "level": 3,
          "title": "移动端",
          "slug": "移动端"
        },
        {
          "level": 3,
          "title": "PC端",
          "slug": "pc端"
        }
      ]
    },
    {
      "title": "图片格式",
      "frontmatter": {},
      "regularPath": "/specification/image_format.html",
      "relativePath": "specification/image_format.md",
      "key": "v-5fcd2cf5",
      "path": "/specification/image_format.html",
      "headers": [
        {
          "level": 2,
          "title": "图片格式",
          "slug": "图片格式-2"
        },
        {
          "level": 3,
          "title": "GIF",
          "slug": "gif"
        },
        {
          "level": 3,
          "title": "PNG",
          "slug": "png"
        },
        {
          "level": 3,
          "title": "JPEG",
          "slug": "jpeg"
        },
        {
          "level": 3,
          "title": "WEBP",
          "slug": "webp"
        },
        {
          "level": 2,
          "title": "团队约定",
          "slug": "团队约定"
        },
        {
          "level": 3,
          "title": "内容图",
          "slug": "内容图"
        },
        {
          "level": 3,
          "title": "背景图",
          "slug": "背景图"
        }
      ]
    },
    {
      "title": "WebApp Meta",
      "frontmatter": {},
      "regularPath": "/specification/html_webapp.html",
      "relativePath": "specification/html_webapp.md",
      "key": "v-1e36c577",
      "path": "/specification/html_webapp.html",
      "headers": [
        {
          "level": 2,
          "title": "WebApp Meta 标签设置(iOS)",
          "slug": "webapp-meta-标签设置-ios"
        },
        {
          "level": 3,
          "title": "Viewport Meta Tag",
          "slug": "viewport-meta-tag"
        },
        {
          "level": 3,
          "title": "Apple-Specific Meta Tag Keys",
          "slug": "apple-specific-meta-tag-keys"
        }
      ]
    },
    {
      "title": "图片引入",
      "frontmatter": {},
      "regularPath": "/specification/image_import.html",
      "relativePath": "specification/image_import.md",
      "key": "v-524e78ce",
      "path": "/specification/image_import.html",
      "headers": [
        {
          "level": 3,
          "title": "CSS Sprites VS Data URIs",
          "slug": "css-sprites-vs-data-uris"
        },
        {
          "level": 2,
          "title": "团队约定",
          "slug": "团队约定"
        },
        {
          "level": 3,
          "title": "CSS Sprites 使用建议",
          "slug": "css-sprites-使用建议"
        },
        {
          "level": 3,
          "title": "Data URIs（base64编码）使用建议",
          "slug": "data-uris-base64编码-使用建议"
        }
      ]
    },
    {
      "title": "图片质量",
      "frontmatter": {},
      "regularPath": "/specification/image_quality.html",
      "relativePath": "specification/image_quality.md",
      "key": "v-f70ba212",
      "path": "/specification/image_quality.html"
    },
    {
      "title": "图片大小",
      "frontmatter": {},
      "regularPath": "/specification/image_size.html",
      "relativePath": "specification/image_size.md",
      "key": "v-75f2a3be",
      "path": "/specification/image_size.html"
    },
    {
      "title": "编码规范",
      "frontmatter": {},
      "regularPath": "/specification/js_code.html",
      "relativePath": "specification/js_code.md",
      "key": "v-7b5d2ab7",
      "path": "/specification/js_code.html",
      "headers": [
        {
          "level": 3,
          "title": "单行代码块",
          "slug": "单行代码块"
        },
        {
          "level": 3,
          "title": "大括号风格",
          "slug": "大括号风格"
        },
        {
          "level": 3,
          "title": "变量命名",
          "slug": "变量命名"
        },
        {
          "level": 3,
          "title": "拖尾逗号",
          "slug": "拖尾逗号"
        },
        {
          "level": 3,
          "title": "逗号空格",
          "slug": "逗号空格"
        },
        {
          "level": 3,
          "title": "逗号风格",
          "slug": "逗号风格"
        },
        {
          "level": 3,
          "title": "计算属性的空格",
          "slug": "计算属性的空格"
        },
        {
          "level": 3,
          "title": "拖尾换行",
          "slug": "拖尾换行"
        },
        {
          "level": 3,
          "title": "函数调用",
          "slug": "函数调用"
        },
        {
          "level": 3,
          "title": "缩进",
          "slug": "缩进"
        },
        {
          "level": 3,
          "title": "对象字面量的键值缩进",
          "slug": "对象字面量的键值缩进"
        },
        {
          "level": 3,
          "title": "构造函数首字母大写",
          "slug": "构造函数首字母大写"
        },
        {
          "level": 3,
          "title": "构造函数的参数",
          "slug": "构造函数的参数"
        },
        {
          "level": 3,
          "title": "链式调用",
          "slug": "链式调用"
        },
        {
          "level": 3,
          "title": "空行",
          "slug": "空行"
        },
        {
          "level": 3,
          "title": "链式赋值",
          "slug": "链式赋值"
        },
        {
          "level": 3,
          "title": "变量声明",
          "slug": "变量声明"
        },
        {
          "level": 3,
          "title": "分号",
          "slug": "分号"
        },
        {
          "level": 3,
          "title": "代码块空格",
          "slug": "代码块空格"
        },
        {
          "level": 3,
          "title": "函数声明的空格",
          "slug": "函数声明的空格"
        },
        {
          "level": 3,
          "title": "操作符的空格",
          "slug": "操作符的空格"
        },
        {
          "level": 3,
          "title": "BOM",
          "slug": "bom"
        }
      ]
    },
    {
      "title": "常见问题",
      "frontmatter": {},
      "regularPath": "/specification/issues.html",
      "relativePath": "specification/issues.md",
      "key": "v-0ce6b537",
      "path": "/specification/issues.html"
    },
    {
      "title": "语言规范",
      "frontmatter": {},
      "regularPath": "/specification/js_language.html",
      "relativePath": "specification/js_language.md",
      "key": "v-370f0e57",
      "path": "/specification/js_language.html",
      "headers": [
        {
          "level": 3,
          "title": "类型",
          "slug": "类型"
        },
        {
          "level": 3,
          "title": "引用",
          "slug": "引用"
        },
        {
          "level": 3,
          "title": "对象",
          "slug": "对象"
        },
        {
          "level": 3,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 3,
          "title": "解构赋值",
          "slug": "解构赋值"
        },
        {
          "level": 3,
          "title": "字符串",
          "slug": "字符串"
        },
        {
          "level": 3,
          "title": "函数",
          "slug": "函数"
        },
        {
          "level": 3,
          "title": "箭头函数",
          "slug": "箭头函数"
        },
        {
          "level": 3,
          "title": "类&构造函数",
          "slug": "类-构造函数"
        },
        {
          "level": 3,
          "title": "模块",
          "slug": "模块"
        },
        {
          "level": 3,
          "title": "迭代器",
          "slug": "迭代器"
        },
        {
          "level": 3,
          "title": "生成器",
          "slug": "生成器"
        },
        {
          "level": 3,
          "title": "对象属性",
          "slug": "对象属性"
        },
        {
          "level": 3,
          "title": "变量声明",
          "slug": "变量声明"
        },
        {
          "level": 3,
          "title": "Hoisting",
          "slug": "hoisting"
        },
        {
          "level": 3,
          "title": "比较运算符&相等",
          "slug": "比较运算符-相等"
        },
        {
          "level": 3,
          "title": "分号",
          "slug": "分号"
        },
        {
          "level": 3,
          "title": "标准特性",
          "slug": "标准特性"
        },
        {
          "level": 3,
          "title": "eval()",
          "slug": "eval"
        },
        {
          "level": 3,
          "title": "with() {}",
          "slug": "with"
        },
        {
          "level": 3,
          "title": "修改内置对象的原型",
          "slug": "修改内置对象的原型"
        }
      ]
    },
    {
      "title": "Vue 风格指南",
      "frontmatter": {},
      "regularPath": "/specification/js_vue.html",
      "relativePath": "specification/js_vue.md",
      "key": "v-0a1d350b",
      "path": "/specification/js_vue.html",
      "headers": [
        {
          "level": 3,
          "title": "参考",
          "slug": "参考"
        }
      ]
    },
    {
      "title": "React&JSX 书写规范",
      "frontmatter": {},
      "regularPath": "/specification/js_react.html",
      "relativePath": "specification/js_react.md",
      "key": "v-2016ac19",
      "path": "/specification/js_react.html",
      "headers": [
        {
          "level": 2,
          "title": "React&JSX 书写规范",
          "slug": "react-jsx-书写规范-2"
        },
        {
          "level": 3,
          "title": "基本规则",
          "slug": "基本规则"
        },
        {
          "level": 3,
          "title": "命名规范",
          "slug": "命名规范"
        },
        {
          "level": 3,
          "title": "Class Component VS Functional Component",
          "slug": "class-component-vs-functional-component"
        },
        {
          "level": 3,
          "title": "对齐",
          "slug": "对齐"
        },
        {
          "level": 3,
          "title": "空格",
          "slug": "空格"
        },
        {
          "level": 3,
          "title": "引号",
          "slug": "引号"
        },
        {
          "level": 3,
          "title": "属性",
          "slug": "属性"
        },
        {
          "level": 3,
          "title": "Refs",
          "slug": "refs"
        },
        {
          "level": 3,
          "title": "圆括号",
          "slug": "圆括号"
        },
        {
          "level": 3,
          "title": "标签",
          "slug": "标签"
        },
        {
          "level": 3,
          "title": "方法",
          "slug": "方法"
        },
        {
          "level": 3,
          "title": "Hooks 书写规范",
          "slug": "hooks-书写规范"
        }
      ]
    },
    {
      "title": "ClassName命名",
      "frontmatter": {},
      "regularPath": "/specification/name_classname.html",
      "relativePath": "specification/name_classname.md",
      "key": "v-604d024d",
      "path": "/specification/name_classname.html",
      "headers": [
        {
          "level": 2,
          "title": "命名原则",
          "slug": "命名原则"
        },
        {
          "level": 2,
          "title": "模块命名",
          "slug": "模块命名"
        },
        {
          "level": 2,
          "title": "常用命名推荐",
          "slug": "常用命名推荐"
        }
      ]
    },
    {
      "title": "目录命名",
      "frontmatter": {},
      "regularPath": "/specification/name_dir.html",
      "relativePath": "specification/name_dir.md",
      "key": "v-a4d3df0e",
      "path": "/specification/name_dir.html",
      "headers": [
        {
          "level": 3,
          "title": "目录命名",
          "slug": "目录命名"
        }
      ]
    },
    {
      "title": "图片命名",
      "frontmatter": {},
      "regularPath": "/specification/name_image.html",
      "relativePath": "specification/name_image.md",
      "key": "v-431159c6",
      "path": "/specification/name_image.html",
      "headers": [
        {
          "level": 3,
          "title": "图片命名",
          "slug": "图片命名"
        }
      ]
    },
    {
      "title": "HTML/CSS文件命名",
      "frontmatter": {},
      "regularPath": "/specification/name_htmlcss.html",
      "relativePath": "specification/name_htmlcss.md",
      "key": "v-e34e29ba",
      "path": "/specification/name_htmlcss.html"
    },
    {
      "title": "测试相关文档",
      "frontmatter": {},
      "regularPath": "/test/",
      "relativePath": "test/README.md",
      "key": "v-46a134ba",
      "path": "/test/"
    },
    {
      "title": "Android相关文档说明",
      "frontmatter": {},
      "regularPath": "/vue/",
      "relativePath": "vue/README.md",
      "key": "v-18eb71d6",
      "path": "/vue/"
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/logo.png",
    "displayAllHeaders": false,
    "activeHeaderLinks": true,
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "编程规约",
        "link": "/specification/"
      },
      {
        "text": "Vue",
        "link": "/vue/"
      },
      {
        "text": "React",
        "link": "/react/"
      },
      {
        "text": "Node.js",
        "link": "/nodejs/"
      },
      {
        "text": "Android",
        "link": "/android/"
      },
      {
        "text": "Electron",
        "link": "/electron/"
      },
      {
        "text": "Git",
        "link": "/git/"
      },
      {
        "text": "移动端",
        "link": "/mobile/"
      },
      {
        "text": "服务器",
        "link": "/server/"
      },
      {
        "text": "网络安全",
        "link": "/safety/"
      },
      {
        "text": "测试",
        "link": "/test/"
      },
      {
        "text": "技术分享",
        "link": "/sharing/"
      }
    ],
    "sidebar": {
      "/specification/": [
        "",
        {
          "title": "命名规范",
          "collapsable": false,
          "children": [
            "name_dir",
            "name_image",
            "name_htmlcss",
            "name_classname"
          ]
        },
        {
          "title": "HTML规范",
          "collapsable": false,
          "children": [
            "html_code",
            "html_note",
            "html_template",
            "html_webapp"
          ]
        },
        {
          "title": "CSS规范",
          "collapsable": false,
          "children": [
            "css_code",
            "css_note",
            "css_query",
            "css_reset",
            "css_sass",
            "css_webkit"
          ]
        },
        {
          "title": "JavaScript 规范",
          "collapsable": false,
          "children": [
            "js_code",
            "js_language",
            "js_vue"
          ]
        },
        {
          "title": "图片规范",
          "collapsable": false,
          "children": [
            "image_format",
            "image_import",
            "image_quality",
            "image_size"
          ]
        }
      ],
      "/react/": [
        "",
        {
          "title": "React基础",
          "collapsable": false,
          "children": [
            "basics_character"
          ]
        }
      ]
    },
    "repo": "Ellison997/Document",
    "repoLabel": "Github",
    "docsRepo": "Ellison997/Document",
    "docsDir": "developing-guideline/docs",
    "docsBranch": "main",
    "editLinks": true,
    "editLinkText": "帮助我们改善此页面！"
  }
}